# Generated by Django 4.0 on 2022-01-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_alter_courierman_additional_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierman',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='deliverystatus',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Dispatched', 'Dispatched'), ('Processing', 'Processing')], max_length=20),
        ),
    ]
