# Generated by Django 4.0 on 2022-01-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_alter_courierman_salary_alter_deliverystatus_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courierman',
            old_name='reduce_salary',
            new_name='reduction_salary',
        ),
    ]
