# Generated by Django 4.0 on 2022-01-04 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_rename_reduce_salary_courierman_reduction_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.receiver'),
        ),
    ]
