# Generated by Django 4.0 on 2022-01-04 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0006_alter_deliverystatus_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('courier_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.courierman')),
            ],
        ),
        migrations.CreateModel(
            name='DailySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('courier_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.courierman')),
            ],
        ),
    ]
