# Generated by Django 3.2.11 on 2022-01-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0007_weeklysalary_dailysalary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailysalary',
            unique_together={('date', 'courier_man')},
        ),
    ]
